### ISSUE TITLE
Enable CI Services / Plugin Publishing

### ISSUE THREAD

**Issue by Nava2** [assertj/assertj-generator-gradle-plugin#1]
Previously, I had Travis and Appveyor setup, but I don't have access to them in this organization. Could you set this up, @joel-costigliola? Both are already configured via yml documents in the repository. Except travis needs some "private" environment variables setup for the gradle keys:

Currently, I own the [plugin](https://plugins.gradle.org/plugin/org.assertj.generator.gradle.plugin) so my keys are used to publish. I'd rather keep my own keys and use an "organization" set of keys. This will mean I need to transfer the plugin, which just involves contacting the gradle folks. 

The plugin publishing info needs to be put into travis as: `GRADLE_PUBLISH_KEY` and `GRADLE_PUBLISH_SECRET`. 
![travis-keys](https://cloud.githubusercontent.com/assets/302365/26587352/112f94aa-4520-11e7-8459-c373d78e2b55.png)

It looks as though you may be able to "reclaim" the plugin if you login with the organization account: https://plugins.gradle.org/docs/reclaiming.

**Comment by joel-costigliola** [comment]
I have created a gradle assertj account, it contains `gradle.publish.key` and `gradle.publish.secret` keys.
I'm not sure though how assertj should reclaim the plugin though, there is no assertj github account, just an organization that I own.

What should I do next ?

**Comment by Nava2** [comment]
Hmm, I think we will have to ask the gradle folks to transfer it or delete it and you can recreate it -- regardless, need some insight from them. What is your "plugins account" handle? I'll need to ask to have it transferred there. 

If the keys are put into the `GRADLE_PUBLISH_XX` env. variables, then after we get the plugin under your account, the build should auto publish when we tag releases. 👍

**Comment by joel-costigliola** [comment]
assertj ;-) https://plugins.gradle.org/u/assertj

**Comment by Nava2** [comment]
It's never good to assume... 😅

**Comment by Nava2** [comment]
This is done, we publish via tags on the `master` branch through Travis.
