### ISSUE TITLE
Documentation states invalid plugin id

### ISSUE THREAD

**Issue by thomaseizinger** [assertj/assertj-generator-gradle-plugin#10]
The README currently states that the plugin can be included via

    plugins { 
        // version matches the version for assertj-generator
        id 'org.assertj.generator.gradle.plugin' version '1.0.0' 
    }

but that plugin id does not exist.

Judging from the other issues there is currently a version that can be included via: `id 'org.assertj.generator' version '0.0.4b'`.

If this is supposed to be the correct id, then the docs should be fixed. And the comment is lying too :)

**Comment by joel-costigliola** [comment]
@Nava2 can you take care of this ?

**Comment by Nava2** [comment]
Yep, for some reason I wasn't watching this repo? Not sure what happened there. I'll look at it tonight!
