### ISSUE TITLE
SoftAssertions generated by assertJ gradle plugin use cglib.proxy.Enhancer

### ISSUE THREAD

**Issue by bvgusak** [assertj/assertj-generator-gradle-plugin#13]
When i'm trying to generate soft assertions with `0.0.6b` gradle plugin, SoftAssertions class uses Enhancer class that isn't present in AssertJ core library `3.9.1`

**Comment by bvgusak** [comment]
It's generally related to migrating to assertj 3.9.1+. Issue can be closed. Sorry for confusion

**Comment by Nava2** [comment]
If it's any consolation, I forgot it was here -- I'm a bit busy as is and haven't been great looking at these 😞.

Thanks for self regulating!
