### ISSUE TITLE
Add support for annotation processors

### ISSUE THREAD

**Issue by thekalinga** [assertj/assertj-generator-gradle-plugin#14]
IDEs like IntellIj IDEA have their own build directory `out` other than gradle build directory `build`.

If the generator generates code only when running gradle task (i.e generates code inside `build` not `out` directory) & there is no annotation processor support, then its painful to use this plugin from IDE

The developers either have to use IDE as a tool to trigger gradle directly (or) taking custom assert generated by this plugin & adding some of them to the source directly & skip code generation subsequently

Tho the second option look reasonable, it would be better if users can annotate their classes that require automatic assert classes to be generated, something similar to lombok/mapstruct & the plugin can look for these annotations & generate the required custom asserts

This way most IDEs can invoke annotation processors & would be much more light weight on the IDEs & ultimately developers

**Comment by Nava2** [comment]
I don't know that the build directory is hard coded, if it is, that is definitely a flaw. However, I believe IntelliJ just changes the build directory to use `out` instead of `build`. I ended up using this in a project that was building with IntelliJ and it worked fine.

**Comment by Nava2** [comment]
This is fully configurable via the `outputDir` property.
