### ISSUE TITLE
Specify source directory in gradle configuration

### ISSUE THREAD

**Issue by ohonc** [assertj/assertj-generator-gradle-plugin#16]
Hello Team!
I'm trying to configure assertj generator on gradle, but i want to specify some classes for generating like in maven configuration http://joel-costigliola.github.io/assertj/assertj-assertions-generator-maven-plugin.html and i have not found how to implement this.
Please share some ideas, it really help me

**Comment by joel-costigliola** [comment]
the assertion generator already supports that, the work here is to find how to propagate the configuration to the generator as we did for the maven plugin.

I'm not a gradle expert and I'm a bit too busy to maintain the gradle plugin but I'm happy to get a PR ;-)

**Comment by Nava2** [comment]
@ohonc I'm going to assume you're long gone at this point. 

The current way to do this is two fold: 

1. Fix up the pattern set filter able logic in #29 and get it working to allow adding include/exclude patterns for source files 
2. Add a feature that will allow specifying class names/package names a la the maven plugin 

Both would work!
