### ISSUE TITLE
Release script fails due to user permissions

### ISSUE THREAD

**Issue by Nava2** [assertj/assertj-generator-gradle-plugin#51]
Failed build: https://github.com/assertj/assertj-generator-gradle-plugin/actions/runs/4790553244

**Comment by Nava2** [comment]
@joel-costigliola it looks like your user doesn't have permission to publish. Are you able to "reclaim" the plugin?

https://plugins.gradle.org/u/Nava2
<img width="363" alt="image" src="https://user-images.githubusercontent.com/302365/234104929-16a8d802-7632-484f-be4d-bb1239795461.png">

**Comment by joel-costigliola** [comment]
There is no plugin to reclaim but it looks like I don't have any.
is there a way to know who owns the plugin?

**Comment by joel-costigliola** [comment]
I see that plugin https://plugins.gradle.org/u/assertj under my name and/or assertj, I logged in gradle as me but it does not seem the same account as https://plugins.gradle.org/u/assertj owner

**Comment by Nava2** [comment]
I'm guessing there-in lies the issue. I can probably request it back to my user, but it seems like we should get it under `assertJ` instead?

**Comment by joel-costigliola** [comment]
that would be the best the way to go

**Comment by Nava2** [comment]
I'm not sure who owns the `assertj` account, can you try to recover it? If not, I can move it back under my account via support as I originally owned it.

**Comment by joel-costigliola** [comment]
I'm not sure how, maybe give it a try first and then we'll share it (if possible) with the assertj team

**Comment by Nava2** [comment]
Wonder if there's better controls now that its 6y later. I feel like organization accounts are probably a thing. Ill reach out to support and ask.

**Comment by joel-costigliola** [comment]
@Nava2 as I was able to reset the password for assertj@gmail.com, I managed to login as owner of https://plugins.gradle.org/u/assertj, I have updated the https://github.com/assertj/assertj-generator-gradle-plugin publish ket and secret env variable.

Is there anything else to do?

**Comment by Nava2** [comment]
I'll rerun the release!

**Comment by Nava2** [comment]
We're good @joel-costigliola ! https://github.com/assertj/assertj-generator-gradle-plugin/actions/runs/4790553244/jobs/8618891271
