### ISSUE TITLE
Use Jakarta annotations

### ISSUE THREAD

**Issue by maciejwalkowiak** [assertj/assertj-generator-gradle-plugin#68]
First of all thanks for getting this project back to life. 

The generated classes are annotated with `@javax.annotation.Generated`. For Java 17+ projects, it should be `@jakarta.annotation.Generated`.

**Comment by maciejwalkowiak** [comment]
I see now that perhaps it needs to be done in the actual generator project first: https://github.com/assertj/assertj-assertions-generator/issues/194

**Comment by Nava2** [comment]
Yep, it's not part of the plugin! Closing this as you've already linked the right issue. 👍🏻

**Comment by timo-abele** [comment]
While we wait for the solution in the maven plugin to be merged, here is how to do the workaround presented [here](https://github.com/assertj/assertj-assertions-generator-maven-plugin/issues/93#issuecomment-1379104371) in gradle:

```gradle kotlin DSL
sourceSets {
    main {
        assertJ {
            templates {
                classes {
                    assertionClass.file("src/main/resources/assertj/templates/_ins_custom_assertion_class_template.txt")
                    entryPoints.assertions.file("src/main/resources/assertj/templates/_ins_standard_assertions_entry_point_class_template.txt")
                }
            }
        }
    }
}
````
