### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by maciejwalkowiak** [assertj/assertj-generator-gradle-plugin#69]
Readme hasn't been updated to 1.0.0. For the record, this is a minimum configuration, but there are more options that should be documented.

```groovy
plugins {
    id 'org.assertj.generator' version '1.0.0'
}

sourceSets {
    main {
        assertJ {
            classDirectories.include "**/com/myapp/domain**"
        }
    }
}
```

**Comment by Nava2** [comment]
You shouldn't need any options passed for minimum usage though. It pulls from the built in Java plugin. 

The docs should be updated for 1.0.0 including the classes directories. I believe it's mostly up to date otherwise. Was there something else missing?
